template:
  name: Terraform Deployment
  type: Stage
  projectIdentifier: default_project
  orgIdentifier: default
  spec:
    type: Custom
    spec:
      execution:
        steps:
          - step:
              type: ShellScript
              name: Terraform Init
              identifier: Terraform_Init
              spec:
                shell: Bash
                executionTarget: {}
                source:
                  type: Inline
                  spec:
                    script: |-
                      cd terraform
                      terraform init
                environmentVariables: []
                outputVariables: []
              timeout: 5m
          - step:
              type: ShellScript
              name: Terraform Plan
              identifier: Terraform_Plan
              spec:
                shell: Bash
                executionTarget: {}
                source:
                  type: Inline
                  spec:
                    script: |-
                      terraform plan \
                          -var 'access_key=$ACCESS_KEY' \
                          -var 'secret_key=$SECRET_KEY' \
                          -out=tfplan
                      terraform show tfplan
                environmentVariables:
                  - name: ACCESS_KEY
                    type: Secret
                    value: account.demo-aws-access-key
                  - name: SECRET_KEY
                    type: Secret
                    value: account.demo-aws-secret-key
                outputVariables: []
              timeout: 5m
          - step:
              type: HarnessApproval
              name: Review Plan
              identifier: Review_Plan
              spec:
                approvalMessage: Please review the following plan and approve the pipeline progression
                includePipelineExecutionHistory: true
                isAutoRejectEnabled: true
                approvers:
                  userGroups:
                    - account._account_all_users
                  minimumCount: 1
                  disallowPipelineExecutor: false
                approverInputs: []
                callbackId: plan_approval
              timeout: 1d
          - step:
              type: ShellScript
              name: Terraform Apply
              identifier: Terraform_Apply
              spec:
                shell: Bash
                executionTarget: {}
                source:
                  type: Inline
                  spec:
                    script: terraform apply tfplan -auto-approve
                environmentVariables: []
                outputVariables: []
              timeout: 5m
  identifier: Terraform_Deployment
  versionLabel: 0.1.0
